export const users = [
    {"nombre": "ana_garcia"},
    {"nombre": "juan_rodriguez"},
    {"nombre": "maria_martinez"},
    {"nombre": "carlos_lopez"},
    {"nombre": "laura_diaz"},
    {"nombre": "pedro_sanchez"},
    {"nombre": "sofia_gomez"},
    {"nombre": "diego_perez"},
    {"nombre": "isabel_fernandez"},
    {"nombre": "javier_ramirez"},
    {"nombre": "carmen_torres"},
    {"nombre": "miguel_vargas"},
    {"nombre": "elena_munoz"},
    {"nombre": "jose_ruiz"},
    {"nombre": "patricia_castro"},
    {"nombre": "roberto_ortega"},
    {"nombre": "natalia_navarro"},
    {"nombre": "francisco_jimenez"},
    {"nombre": "alicia_luna"},
    {"nombre": "gabriel_herrera"},
    {"nombre": "beatriz_gutierrez"},
    {"nombre": "antonio_medina"},
    {"nombre": "paula_flores"},
    {"nombre": "ricardo_alvarado"}
]
  